# Generated by Django 5.2.3 on 2025-07-01 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument", models.CharField(max_length=100)),
                ("position_size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("entry_date", models.DateField()),
                ("exit_date", models.DateField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("win", "Win"), ("loss", "Loss"), ("open", "Open")],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
